### ISSUE TITLE
Please fix the errors for the latest 4.18.+

### ISSUE THREAD

**Issue by Membest15** [vecnavium-pm-pl/Slapper#68] opened 2023-04-05 07:16 UTC
#67  #66 
``please update/fix for the latest "4.18.+"``
we're stuck in the hole🥵😭

**Comment by cosmicnebula200** [comment] 2023-04-05 07:44
Just because those emojis, it is never being updated GG

**Comment by DuoIncure** [comment] 2023-04-05 10:25
Duplicate of #66

**Closed as completed** 2023-04-05 14:24 UTC
